name: Continous Integration and Testing

on:
  push:
    branches: "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
      # env:
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # MYSQL_DATABASE: laravel
      # ports:
      #  - 33306:3306
      #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Config Clearing
        run: php artisan config:clear

      - name: Cache Clearing
        run: php artisan cache:clear

      - name: Route Clearing
        run: php artisan route:clear

      - name: Route Clearing
        run: php artisan optimize:clear

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Config
        run: php artisan config:clear
      - name: MigrateDB
        run: php artisan migrate:fresh
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.pgsql
      #- name: Generate Scribe Documentation
      #env:
      #APP_URL: https://backend-ngts.onrender.com/
      #run: php artisan scribe:generate
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
            DB_CONNECTION: mysql
            DB_DATABASE: database/database.mysql
        run: php artisan test
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.gridape.com
          username: hng@hng.gridape.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /